MOC:
  ImageOptimizer:
    useGlobalBinary: false # use globally installed binaries for all formats instead
    globalBinaryPath: ''
    formats:
      jpg:
        enabled: true
        progressive: true # whether or not to server progressive jpgs
        useGlobalBinary: false # use globally installed binary for jpegtran instead
      png:
        enabled: true
        optimizationLevel: 2 # optimization level (0-7)
        useGlobalBinary: false # use globally installed binary for optipng instead
      gif:
        enabled: true
        optimizationLevel: 2 # optimization level (1-3)
        useGlobalBinary: false # use globally installed binary for gifsicle instead
      svg:
        enabled: true
        pretty: false # keep the output readable
        useGlobalBinary: false # use globally installed binary for svgo instead